# Generated by Django 2.1.5 on 2019-02-05 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CargoScored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('got_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.CargoFrom')),
            ],
        ),
        migrations.CreateModel(
            name='GameTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HatchFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HatchScored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('got_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.HatchFrom')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEndStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MatchStartStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PreloadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutedMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('end_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.MatchEndStatus')),
                ('scouted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('start_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.MatchStartStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('name', models.CharField(default='UNAMED', max_length=200)),
                ('event_code', models.CharField(default='UNAMED', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='in_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoutserver.Tournament'),
        ),
        migrations.AddField(
            model_name='scoutedmatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.Team'),
        ),
        migrations.AddField(
            model_name='scoutedmatch',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.Tournament'),
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.Tournament'),
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.Team'),
        ),
        migrations.AddField(
            model_name='hatchscored',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoutserver.ScoutedMatch'),
        ),
        migrations.AddField(
            model_name='hatchscored',
            name='scored_where',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.ScoreLocation'),
        ),
        migrations.AddField(
            model_name='hatchscored',
            name='when',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.GameTime'),
        ),
        migrations.AddField(
            model_name='cargoscored',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoutserver.ScoutedMatch'),
        ),
        migrations.AddField(
            model_name='cargoscored',
            name='scored_where',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.ScoreLocation'),
        ),
        migrations.AddField(
            model_name='cargoscored',
            name='when',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.GameTime'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoutserver.Team'),
        ),
    ]
