# Generated by Django 2.1.5 on 2019-02-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmatch',
            name='alliance',
            field=models.CharField(default='red', max_length=255),
            preserve_default=False,
        ),
    ]
