# Generated by Django 2.1.5 on 2019-02-02 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='in_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoutserver.Tournament'),
        ),
    ]
