# Generated by Django 2.1.5 on 2019-02-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutserver', '0002_team_in_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreloadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
