# Generated by Django 2.1.5 on 2019-02-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoutserver', '0002_scheduledmatch_alliance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduledmatch',
            unique_together={('team', 'event', 'match_number')},
        ),
    ]
