# Generated by Django 2.1.5 on 2019-02-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutserver', '0004_auto_20190207_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='cargoscored',
            name='got_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.FromLocation'),
        ),
        migrations.AlterField(
            model_name='hatchscored',
            name='got_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.FromLocation'),
        ),
        migrations.DeleteModel(
            name='CargoFrom',
        ),
        migrations.DeleteModel(
            name='HatchFrom',
        ),
    ]
