# Generated by Django 2.1.7 on 2019-02-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutserver', '0005_auto_20190208_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutedmatch',
            name='card',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scoutserver.Cards'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoutedmatch',
            name='preload',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scoutserver.PreloadStatus'),
            preserve_default=False,
        ),
    ]
