# Generated by Django 2.1.7 on 2019-02-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutserver', '0006_auto_20190215_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(max_length=255)),
                ('got_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.FromLocation')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoutserver.ScoutedMatch')),
                ('scored_where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.ScoreLocation')),
                ('when', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutserver.GameTime')),
            ],
        ),
        migrations.RemoveField(
            model_name='cargoscored',
            name='got_from',
        ),
        migrations.RemoveField(
            model_name='cargoscored',
            name='match',
        ),
        migrations.RemoveField(
            model_name='cargoscored',
            name='scored_where',
        ),
        migrations.RemoveField(
            model_name='cargoscored',
            name='when',
        ),
        migrations.RemoveField(
            model_name='hatchscored',
            name='got_from',
        ),
        migrations.RemoveField(
            model_name='hatchscored',
            name='match',
        ),
        migrations.RemoveField(
            model_name='hatchscored',
            name='scored_where',
        ),
        migrations.RemoveField(
            model_name='hatchscored',
            name='when',
        ),
        migrations.DeleteModel(
            name='CargoScored',
        ),
        migrations.DeleteModel(
            name='HatchScored',
        ),
    ]
