# Generated by Django 2.1.7 on 2019-02-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutserver', '0007_auto_20190216_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutedmatch',
            name='auto_move',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
