# Generated by Django 2.1.5 on 2019-03-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutserver', '0008_scoutedmatch_auto_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutedmatch',
            name='playedD',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
